'use strict';
const LABELS={cpu:'Procesador',board:'Placa base',ram:'Memoria RAM',disk:'Almacenamiento',gpu:'Tarjeta gráfica',psu:'Fuente',case:'Caja',cooler:'Refrigeración',monitor:'Pantalla'};
const ALL=Object.values(CATALOG).flat();
const byId=id=>ALL.find(x=>x.id===id);
const fresh=()=>({version:1,name:'',profile:0,mode:'reto',prices:'fixed',step:'encargo',selected:{},mounted:{},wires:{},safety:false,power:false,orientation:'',ramSlots:'',thermal:false,notes:{},research:{},comparison:'',defense:'',needs:'',attempts:0,hints:0,history:[],tests:[],videoType:'HDMI',submitted:false,boot:null});
function parts(s){const p={};for(const k in LABELS)p[k]=byId(s.selected[k]);if(s.selected.gpu==='integrated')p.gpu={id:'integrated',name:'Gráficos integrados',price:0,integrated:true,tier:0,ports:['HDMI','DP']};if(s.selected.cooler==='stock')p.cooler={id:'stock',name:'Disipador incluido',price:0,stock:true,height:p.cpu?.id==='C6'?96:60,sockets:p.cpu?[p.cpu.socket]:[]};if(s.selected.monitor==='reuse')p.monitor={id:'reuse',name:'Monitor del cliente',price:0,reuse:true,ports:['HDMI','DP'],size:24,res:s.profile===4?'2560 × 1440':'1920 × 1080'};return p;}
function validOffer(r,p){return !!r&&Number.isFinite(Number(r.price))&&Number(r.price)>0&&Number(r.price)<p.price&&/^https?:\/\/[^\s/]+/i.test(r.url||'')&&!!r.shop?.trim();}
function priceOf(s,p){if(!p||['integrated','stock','reuse'].includes(p.id))return 0;return p.price;}
function total(s){return Object.values(parts(s)).reduce((n,p)=>n+priceOf(s,p),0);}
function compatibility(s){const p=parts(s),o=[];const check=(id,title,ok,detail,level='error')=>o.push({id,title,ok,detail,level});
 for(const k in LABELS)check('missing-'+k,LABELS[k],!!p[k],p[k]?'Seleccionado: '+p[k].name:'Falta elegir '+LABELS[k].toLowerCase());
 if(p.cpu&&p.board){check('socket','CPU y placa',p.cpu.socket===p.board.socket,`${p.cpu.socket} frente a ${p.board.socket}.`);check('support','Soporte de CPU',p.board.support.includes(p.cpu.series),`Familia ${p.cpu.series}; placa preparada para ${p.board.support.join(', ')}. Se supone firmware compatible instalado.`);}
 if(p.ram&&p.board){check('ddr','Generación de RAM',p.ram.ddr===p.board.ddr,`RAM DDR${p.ram.ddr}; placa DDR${p.board.ddr}.`);check('capacity','Capacidad y ranuras',p.ram.cap<=p.board.maxram&&p.ram.modules<=p.board.slots,`${p.ram.cap} GB en ${p.ram.modules} módulos; límite de práctica ${p.board.maxram} GB y ${p.board.slots} ranuras.`);}
 if(p.ram&&p.board&&s.mounted.ram){const ideal=p.ram.modules===1?(p.board.slots===2?'A1':'A2'):(p.board.slots===2?'A1 + B1':'A2 + B2');if(s.ramSlots!==ideal)check('ramplacement','Distribución de RAM',false,'El equipo puede arrancar, pero el manual recomienda '+ideal+' para este kit. Dos módulos en un mismo canal no aprovechan el doble canal.', 'warning');}
 if(p.disk&&p.board)check('storage','Conexión de almacenamiento',p.disk.interface==='NVMe'?p.board.m2>0:p.board.sata>0,`${p.disk.interface}; ${p.board.m2} M.2 y ${p.board.sata} SATA disponibles.`);
 if(p.disk?.interface==='NVMe'&&p.cpu&&p.board&&p.disk.gen>Math.min(p.board.gen,p.cpu.pcie))check('pcie','Velocidad PCIe',false,`El SSD PCIe ${p.disk.gen}.0 puede funcionar a PCIe ${Math.min(p.board.gen,p.cpu.pcie)}.0. Es compatible, con menor ancho de banda.`, 'warning');
 if(p.board&&p.case)check('form','Placa y caja',p.case.forms.includes(p.board.form),`${p.board.form}; la caja admite ${p.case.forms.join(', ')}.`);
 if(p.gpu?.integrated&&p.cpu)check('graphics','Gráficos integrados',p.cpu.igpu,p.cpu.igpu?'La CPU dispone de gráficos.':'Esta CPU no tiene gráficos: necesita una GPU dedicada.');
 if(p.gpu&&!p.gpu.integrated&&p.case){check('gpufit','Espacio para la GPU',p.gpu.length<=p.case.gpu&&p.gpu.thick<=p.case.thick,`GPU: ${p.gpu.length} mm de largo y ${p.gpu.thick} mm de grosor; límites: ${p.case.gpu} y ${p.case.thick} mm.`);}
 if(p.psu&&p.case)check('psufit','Fuente y caja',(p.psu.form===p.case.psu||(p.psu.form==='SFX'&&p.case.psu==='ATX'))&&p.psu.length<=p.case.psulen,`${p.psu.form}, ${p.psu.length} mm; caja ${p.case.psu}, hasta ${p.case.psulen} mm. SFX en ATX utiliza adaptador.`);
 if(p.gpu&&!p.gpu.integrated&&p.psu){check('power','Margen de alimentación',p.psu.power>=p.gpu.recommend,`${p.psu.power} W disponibles; fabricante de la GPU recomienda ${p.gpu.recommend} W para el sistema. No implica que no pueda encender con menos.`, 'warning');check('pcipins','Conectores de GPU',p.psu.pins>=p.gpu.pins,`${p.gpu.pins} conectores PCIe de 8 pines requeridos; ${p.psu.pins} disponibles.`);}
 if(p.cooler&&p.cpu){check('coolersocket','Disipador y CPU',p.cooler.stock?p.cpu.stock:p.cooler.sockets.includes(p.cpu.socket),p.cooler.stock?(p.cpu.stock?'La CPU en caja incluye disipador.':'Esta CPU no incluye disipador.'):`Admite ${p.cooler.sockets.join(', ')}; CPU ${p.cpu.socket}.`);}
 if(p.cooler&&p.case)check('coolerfit','Altura del disipador',p.cooler.height<=p.case.cool,`${p.cooler.height} mm frente a ${p.case.cool} mm disponibles.`);
 if(p.cooler?.low&&p.cpu?.tier>=2)check('thermalmargin','Margen térmico',false,'El disipador de perfil bajo puede reducir el margen térmico en cargas sostenidas. Revisa la compatibilidad térmica del fabricante; no se simulan temperaturas.', 'warning');
 if(p.gpu&&!p.gpu.integrated&&p.case?.fans<2)check('airflow','Ventilación',false,'La caja incluye un solo ventilador. Para este encargo con GPU se recomienda otra caja del catálogo con dos o más.', 'warning');
 if(PROFILES[s.profile].screen&&p.monitor?.reuse)check('monitorpurchase','Pantalla del encargo',false,'Este cliente necesita comprar pantalla: debe incluirse en el presupuesto.');
 return o;}
function suitability(s){const p=parts(s),pr=PROFILES[s.profile],out=[];const c=(title,ok,detail)=>out.push({title,ok:!!ok,detail});
 c('Memoria suficiente',p.ram?.cap>=pr.ram,`Necesita al menos ${pr.ram} GB.`);c('Almacenamiento adecuado',p.disk?.kind==='SSD'&&p.disk.cap>=pr.disk&&(s.profile!==4||p.disk.interface==='NVMe'),`Necesita SSD de al menos ${pr.disk} GB${s.profile===4?' NVMe':''}.`);c('CPU para el encargo',p.cpu?.tier>=pr.cpu,'Clasificación didáctica por familias del catálogo; no es un benchmark.');
 c('Capacidad gráfica',pr.gpu===0?(p.gpu?.integrated?p.cpu?.igpu:!!p.gpu):p.gpu?.tier>=pr.gpu,pr.gpu?'Revisa el nivel gráfico que exige el cliente. No se garantizan FPS ni rendimiento de un juego concreto.':'Para este uso no hace falta comprar una GPU dedicada.');
 if(pr.wifi)c('Wi-Fi y Bluetooth',p.board?.wifi&&p.board?.bt,'Ambos deben estar incluidos en la placa elegida en este catálogo.');
 if(pr.compact)c('Caja compacta',p.case?.compact,'En este catálogo: Q300L o NR200P.');
 if(pr.screen)c('Pantalla adecuada',p.monitor&&!p.monitor.reuse&&(s.profile===2?p.monitor.size>=27&&p.monitor.res==='2560 × 1440'&&p.monitor.color:p.monitor.size>=23&&p.monitor.size<=24.5),'Comprueba tamaño, resolución y, para Lucía, calibración y cobertura del color.');
 if(pr.gpu)c('Ventilación prevista',p.case?.fans>=2,'Se pide una caja con dos o más ventiladores incluidos.');
 c('Presupuesto',Object.keys(s.selected).length===9&&total(s)<=pr.budget,`${total(s).toFixed(2)} € de ${pr.budget} €; precios fijos de la actividad.`);
 return out;}
function requiredMounts(s){return Object.keys(parts(s)).filter(k=>parts(s)[k]&&!['integrated','stock','reuse'].includes(parts(s)[k].id)||parts(s)[k]?.id==='stock');}
function cableSpecs(s){const p=parts(s),a=[
 ['atx','Electricidad para la placa','Fuente de alimentación','Placa base: conector grande','Alimenta los circuitos principales de la placa.','ATX de 24 pines'],
 ['eps','Electricidad para el procesador','Fuente de alimentación','Placa base: junto al procesador','La energía llega al procesador a través de la placa, no con un cable conectado directamente a la CPU.','CPU / EPS de 4+4 pines'],
 ['cpufan','Ventilador del procesador','Ventilador colocado sobre el procesador','Placa base: conexión del ventilador de CPU','Permite alimentar y regular el ventilador del disipador.','CPU_FAN'],
 ['casefan','Ventiladores de la caja','Ventiladores de la caja','Placa base: conexión de ventiladores de caja','Mueven el aire dentro del equipo. Se conectan como grupo en esta simulación.','SYS_FAN o hub compatible'],
 ['front','Botón de encendido','Botón frontal de la caja','Placa base: conexión del botón de encendido','Permite que el botón de la caja ordene encender el equipo.','POWER SW / PWR_SW'],
 ['usb','Teclado','Cable del teclado','Puerto USB trasero del ordenador','Permite usar el teclado para configurar el equipo.','USB']
 ];
 if(p.gpu&&!p.gpu.integrated)for(let i=1;i<=p.gpu.pins;i++)a.push(['gpu'+i,'Electricidad para la gráfica'+(p.gpu.pins>1?' · cable '+i:''),'Fuente de alimentación','Tarjeta gráfica: toma de corriente '+i,'La tarjeta elegida necesita '+p.gpu.pins+' cable(s) de alimentación adicional.','PCIe de 6+2 pines']);
 if(p.disk?.interface==='SATA')a.push(['sata','Datos del almacenamiento','Placa base: puerto para almacenamiento','Disco: conexión de datos','Transporta información entre la placa y la unidad.','SATA de datos'],['satapower','Electricidad para el almacenamiento','Fuente de alimentación','Disco: conexión de corriente','Da energía al disco. No sustituye al cable de datos.','SATA de alimentación']);
 return a.map(([id,title,from,to,why,tech])=>({id,title,from,to,why,tech}));}
function boot(s){const p=parts(s),m=s.mounted,w=s.wires;
 if(!s.power)return {code:'off',title:'Sin alimentación',text:'No hay reacción al pulsar el botón de encendido.',hint:'Comprueba la conexión a la red y el interruptor de la fuente.'};
 if(!m.psu||!m.board||!w.atx||!w.front)return {code:'off',title:'El equipo no enciende',text:'No se observa actividad al pulsar el botón.',hint:'Revisa fuente, electricidad para la placa y cable del botón de encendido.'};
 if(!m.cpu||!w.eps)return {code:'cpu',title:'POST detenido · CPU',text:'Hay alimentación, pero la comprobación del procesador no se completa.',hint:'Comprueba el procesador y su cable de electricidad desde la fuente hasta la placa.'};
 if(!m.ram)return {code:'dram',title:'POST detenido · DRAM',text:'La memoria no se detecta.',hint:'Comprueba que has instalado el kit de RAM y elegido las ranuras adecuadas.'};
 if(!m.cooler||!s.thermal||!w.cpufan)return {code:'fan',title:'CPU FAN / refrigeración',text:'El sistema solicita revisar la refrigeración antes de continuar.',hint:'Comprueba disipador, pasta térmica y cable del ventilador del procesador. Es una protección didáctica; las placas reales pueden reaccionar de otra forma.'};
 const hard=compatibility(s).find(c=>!c.ok&&c.level==='error'&&!c.id.startsWith('missing-')&&c.id!=='monitorpurchase');
 if(hard)return {code:'hardware',title:'POST no completado',text:'El equipo presenta una incompatibilidad pendiente.',hint:hard.title+': '+hard.detail};
 if(!p.gpu||(!p.gpu.integrated&&(!m.gpu||Array.from({length:p.gpu.pins},(_,i)=>!w['gpu'+(i+1)]).some(Boolean))))return {code:'vga',title:'POST detenido · VGA',text:'No se inicializa la tarjeta gráfica seleccionada.',hint:'Revisa instalación de la GPU y todos sus conectores de alimentación.'};
 if(!w.video||!p.monitor||(!p.monitor.reuse&&!m.monitor)||w.video==='board'&&!p.cpu?.igpu||w.video==='gpu'&&p.gpu.integrated)return {code:'display',title:'Pantalla sin señal',text:'El equipo tiene actividad, pero el monitor no recibe imagen.',hint:'Comprueba pantalla, cable de vídeo y salida elegida. La salida de la placa necesita una CPU con gráficos.'};
 const disk=m.disk&&(p.disk?.interface==='NVMe'||w.sata&&w.satapower);
 return {code:'uefi',title:'UEFI · Hardware detectado',text:disk?'POST completado. No se ha instalado ningún sistema operativo.':'POST completado. No se detecta una unidad de almacenamiento.',disk:!!disk,hint:disk?'El montaje llega a UEFI. Aún debes comprobar el encargo y preparar la entrega.':'Revisa el montaje del almacenamiento y, si es SATA, sus dos conexiones.'};}
function validateImport(x){if(!x||x.version!==1||!Number.isInteger(x.profile)||!PROFILES[x.profile]||!['guiado','reto','evaluacion'].includes(x.mode)||!['fixed','real'].includes(x.prices))throw Error('Formato de práctica no válido.');const clean=fresh();for(const k of ['name','needs','comparison','defense'])clean[k]=String(x[k]||'').slice(0,20000);Object.assign(clean,{profile:x.profile,mode:'reto',prices:'fixed'});for(const k in LABELS){const id=x.selected?.[k];if(id&&!CATALOG[k].some(v=>v.id===id)&&!({gpu:'integrated',cooler:'stock',monitor:'reuse'}[k]===id))throw Error('Componente desconocido.');if(id)clean.selected[k]=id;if(Object.hasOwn(x.mounted||{},k))clean.mounted[k]=!!x.mounted[k];}
 for(const k of ['safety','power','thermal','submitted'])clean[k]=!!x[k];clean.orientation=String(x.orientation||'');clean.ramSlots=String(x.ramSlots||'');for(const c of cableSpecs(clean))if(Object.hasOwn(x.wires||{},c.id))clean.wires[c.id]=!!x.wires[c.id];if(['board','gpu'].includes(x.wires?.video))clean.wires.video=x.wires.video;for(const c of ALL){const r=x.research?.[c.id];if(r)clean.research[c.id]={price:Number.isFinite(Number(r.price))&&Number(r.price)>=0?String(r.price):'',shop:String(r.shop||'').slice(0,200),url:String(r.url||'').slice(0,2000),...(r.date?{date:String(r.date)}:{})};}for(const k of ['socket','ddr','storage','form','power','gpufit','coolersocket'])clean.notes[k]=String(x.notes?.[k]||'').slice(0,5000);clean.attempts=Math.max(0,Math.min(10000,Number(x.attempts)||0));clean.hints=Math.max(0,Math.min(10000,Number(x.hints)||0));clean.history=Array.isArray(x.history)?x.history.map(v=>String(v)):[];clean.step=['encargo','catalogo','montaje','prueba','entrega'].includes(x.step)?x.step:'encargo';clean.tests=Array.isArray(x.tests)?JSON.parse(JSON.stringify(x.tests)):[];clean.videoType=['HDMI','DP'].includes(x.videoType)?x.videoType:'HDMI';if(x.boot&&typeof x.boot==='object'&&typeof x.boot.code==='string')clean.boot=boot(clean);return clean;}
